import { Ionicons } from '@expo/vector-icons'
import { useLocalSearchParams, useRouter } from 'expo-router'
import React, { useEffect } from 'react'
import {
  Dimensions,
  Linking,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { BiasTag } from '../../components/ui/BiasTag'
import { CategoryPill } from '../../components/ui/CategoryPill'
import { ArticleSkeleton } from '../../components/ui/Skeleton'
import { Font, Radius, Spacing } from '../../constants/theme'
import { useTheme } from '../../context/ThemeContext'
import { useArticle } from '../../hooks/useNews'
import { recordView } from '../../lib/preferences'

const { width: W } = Dimensions.get('window')

export default function ArticleScreen() {
  const { id }      = useLocalSearchParams<{ id: string }>()
  const router      = useRouter()
  const { colors }  = useTheme()
  const { data, isLoading } = useArticle(Number(id))

  useEffect(() => {
    if (data?.id) recordView(data.id, data.author)
  }, [data?.id])

  if (isLoading) {
    return (
      <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}>
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={22} color={colors.accent} />
        </TouchableOpacity>
        <ScrollView contentContainerStyle={styles.content}>
          {Array(3).fill(null).map((_, i) => <ArticleSkeleton key={i} />)}
        </ScrollView>
      </SafeAreaView>
    )
  }

  if (!data) return null

  const tags = data.tags ? data.tags.split(',').filter(Boolean) : []

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}>
      {/* Back */}
      <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
        <Ionicons name="arrow-back" size={22} color={colors.accent} />
        <Text style={[styles.backText, { color: colors.accent }]}>Feed</Text>
      </TouchableOpacity>

      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        {/* Meta row */}
        <View style={styles.metaRow}>
          <CategoryPill label={data.category} />
          <BiasTag bias={data.bias} confidence={data.bias_confidence} />
        </View>

        {/* Title */}
        <Text style={[styles.title, { color: colors.text }]}>{data.title}</Text>

        {/* Source bar */}
        <View style={[styles.sourceBar, { borderColor: colors.border }]}>
          <Text style={[styles.sourceName, { color: colors.accent }]}>{data.source_name}</Text>
          <Text style={[styles.readTime, { color: colors.muted }]}>{Math.ceil(data.read_time / 60)} min read</Text>
        </View>

        {/* AI Summary */}
        {data.summary && (
          <View style={[styles.summaryBox, { backgroundColor: `${colors.accent}12`, borderLeftColor: colors.accent }]}>
            <View style={styles.summaryLabelRow}>
              <View style={[styles.aiDot, { backgroundColor: colors.accent }]} />
              <Text style={[styles.summaryLabel, { color: colors.accent }]}>AI Summary</Text>
            </View>
            <Text style={[styles.summaryText, { color: colors.text }]}>{data.summary}</Text>
          </View>
        )}

        {/* Bias box */}
        {data.bias_reason && data.bias !== 'neutral' && (
          <View style={[styles.biasBox, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <Text style={[styles.biasLabel, { color: colors.muted }]}>Bias Analysis</Text>
            <Text style={[styles.biasText, { color: colors.muted }]}>{data.bias_reason}</Text>
          </View>
        )}

        {/* Tags */}
        {tags.length > 0 && (
          <View style={styles.tagsWrap}>
            {tags.map(t => (
              <View key={t} style={[styles.tag, { backgroundColor: colors.card, borderColor: colors.border }]}>
                <Text style={[styles.tagText, { color: colors.muted }]}>#{t.trim()}</Text>
              </View>
            ))}
          </View>
        )}

        {/* CTA */}
        <TouchableOpacity
          style={[styles.readBtn, { backgroundColor: colors.accent }]}
          onPress={() => Linking.openURL(data.url)}
          activeOpacity={0.8}
        >
          <Text style={styles.readBtnText}>Read Full Article</Text>
          <Ionicons name="open-outline" size={16} color="#fff" />
        </TouchableOpacity>

        {/* Nuvera footer */}
        <Text style={[styles.nuveraNote, { color: colors.border }]}>
          Summary generated by Verax AI · The truth-teller.
        </Text>
      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  safe:    { flex: 1 },
  backBtn: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: Spacing.md,
    paddingVertical:   Spacing.sm,
    gap:               6,
  },
  backText: {
    fontSize:   Font.size.md,
    fontWeight: Font.weight.medium,
  },
  content: {
    paddingHorizontal: Spacing.md,
    paddingBottom:     Spacing.xl * 2,
    width:             W,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems:    'center',
    gap:           Spacing.sm,
    marginBottom:  Spacing.md,
  },
  title: {
    fontSize:      Font.size.xl + 2,
    fontWeight:    Font.weight.bold,
    lineHeight:    (Font.size.xl + 2) * 1.3,
    letterSpacing: -0.4,
    marginBottom:  Spacing.sm,
  },
  sourceBar: {
    flexDirection:     'row',
    justifyContent:    'space-between',
    alignItems:        'center',
    paddingVertical:   Spacing.sm,
    borderTopWidth:    1,
    borderBottomWidth: 1,
    marginBottom:      Spacing.lg,
  },
  sourceName: {
    fontSize:   Font.size.sm,
    fontWeight: Font.weight.semibold,
  },
  readTime: {
    fontSize: Font.size.xs,
  },
  summaryBox: {
    borderRadius:    Radius.md,
    padding:         Spacing.md,
    marginBottom:    Spacing.md,
    borderLeftWidth: 3,
  },
  summaryLabelRow: {
    flexDirection: 'row',
    alignItems:    'center',
    gap:           6,
    marginBottom:  Spacing.xs,
  },
  aiDot: {
    width:        8,
    height:       8,
    borderRadius: 4,
  },
  summaryLabel: {
    fontSize:      Font.size.xs,
    fontWeight:    Font.weight.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  summaryText: {
    fontSize:   Font.size.md,
    lineHeight: Font.size.md * 1.7,
  },
  biasBox: {
    borderRadius:  Radius.md,
    padding:       Spacing.md,
    marginBottom:  Spacing.md,
    borderWidth:   1,
  },
  biasLabel: {
    fontSize:      Font.size.xs,
    fontWeight:    Font.weight.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom:  Spacing.xs,
  },
  biasText: {
    fontSize:   Font.size.sm,
    lineHeight: Font.size.sm * 1.6,
  },
  tagsWrap: {
    flexDirection: 'row',
    flexWrap:      'wrap',
    gap:           Spacing.xs,
    marginBottom:  Spacing.lg,
  },
  tag: {
    borderWidth:       1,
    paddingHorizontal: Spacing.sm,
    paddingVertical:   3,
    borderRadius:      Radius.sm,
  },
  tagText: {
    fontSize: Font.size.xs,
  },
  readBtn: {
    flexDirection:   'row',
    alignItems:      'center',
    justifyContent:  'center',
    gap:             Spacing.xs,
    paddingVertical: Spacing.md + 2,
    borderRadius:    Radius.md,
    marginBottom:    Spacing.md,
  },
  readBtnText: {
    color:      '#1a1a2e',
    fontSize:   Font.size.md,
    fontWeight: Font.weight.semibold,
  },
  nuveraNote: {
    textAlign: 'center',
    fontSize:  Font.size.xs,
    marginTop: Spacing.sm,
  },
})
